import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({ 
  screenContainer: { 
    flex: 1, 
    justifyContent: 'center', 
    alignItems: 'center', 
    padding: 20, 
  }, 
  headerText: { 
    fontSize: 28, 
    fontWeight: '800', 
    marginBottom: 32,
    letterSpacing: 1,
    textShadowColor: 'rgba(0, 0, 0, 0.1)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  }, 
  mainButton: { 
    paddingVertical: 16, 
    paddingHorizontal: 32, 
    borderRadius: 30, 
    elevation: 8,
    shadowColor: '#000', 
    shadowOffset: { width: 0, height: 4 }, 
    shadowOpacity: 0.25, 
    shadowRadius: 8,
  }, 
  buttonText: { 
    color: '#fff', 
    fontSize: 18, 
    fontWeight: '700',
    letterSpacing: 0.5,
  }, 
  modalOverlay: { 
    flex: 1, 
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center', 
    alignItems: 'center', 
  }, 
  modalCard: { 
    width: '85%', 
    backgroundColor: '#fff', 
    borderRadius: 28, 
    padding: 0,
    alignItems: 'center', 
    overflow: 'hidden',
    elevation: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
  }, 
  colorIndicator: { 
    width: '100%', 
    height: 8, 
    position: 'absolute', 
    top: 0,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
  }, 
  modalTitle: { 
    fontSize: 24, 
    fontWeight: '800', 
    marginTop: 28, 
    marginBottom: 12, 
    color: '#1a1a1a',
    letterSpacing: -0.3,
  }, 
  modalBody: { 
    fontSize: 15, 
    textAlign: 'center', 
    color: '#666', 
    lineHeight: 22, 
    marginBottom: 28,
    paddingHorizontal: 24,
  }, 
  closeButton: { 
    backgroundColor: '#f8f8f8',
    paddingVertical: 12, 
    paddingHorizontal: 32, 
    borderRadius: 40,
    marginBottom: 28,
    borderWidth: 0,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  }, 
  closeButtonText: { 
    fontWeight: '700',
    fontSize: 14,
    letterSpacing: 1,
  },
  modalContent: {
    alignItems: 'center',
    width: '100%',
  }
});

export default styles;